//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by hand (normally controller-gen). DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineSecurityPolicy) DeepCopyInto(out *PipelineSecurityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineSecurityPolicy.
func (in *PipelineSecurityPolicy) DeepCopy() *PipelineSecurityPolicy {
	if in == nil {
		return nil
	}
	out := new(PipelineSecurityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineSecurityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineSecurityPolicyList) DeepCopyInto(out *PipelineSecurityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PipelineSecurityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineSecurityPolicyList.
func (in *PipelineSecurityPolicyList) DeepCopy() *PipelineSecurityPolicyList {
	if in == nil {
		return nil
	}
	out := new(PipelineSecurityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineSecurityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineSecurityReport) DeepCopyInto(out *PipelineSecurityReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineSecurityReport.
func (in *PipelineSecurityReport) DeepCopy() *PipelineSecurityReport {
	if in == nil {
		return nil
	}
	out := new(PipelineSecurityReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineSecurityReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineSecurityReportList) DeepCopyInto(out *PipelineSecurityReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PipelineSecurityReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineSecurityReportList.
func (in *PipelineSecurityReportList) DeepCopy() *PipelineSecurityReportList {
	if in == nil {
		return nil
	}
	out := new(PipelineSecurityReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineSecurityReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineSecurityPolicySpec) DeepCopyInto(out *PipelineSecurityPolicySpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	out.Thresholds = in.Thresholds
	out.EvaluationInterval = in.EvaluationInterval
	if in.Enforcement != nil {
		in, out := &in.Enforcement, &out.Enforcement
		*out = make([]EnforcementAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RuleOverrides != nil {
		in, out := &in.RuleOverrides, &out.RuleOverrides
		*out = make([]RuleOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineSecurityPolicySpec.
func (in *PipelineSecurityPolicySpec) DeepCopy() *PipelineSecurityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(PipelineSecurityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineSecurityPolicyStatus) DeepCopyInto(out *PipelineSecurityPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineSecurityPolicyStatus.
func (in *PipelineSecurityPolicyStatus) DeepCopy() *PipelineSecurityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PipelineSecurityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineSecurityReportStatus) DeepCopyInto(out *PipelineSecurityReportStatus) {
	*out = *in
	in.LastEvaluated.DeepCopyInto(&out.LastEvaluated)
	out.Source = in.Source
	out.Summary = in.Summary
	if in.CorrelatedWorkloads != nil {
		in, out := &in.CorrelatedWorkloads, &out.CorrelatedWorkloads
		*out = make([]WorkloadRef, len(*in))
		copy(*out, *in)
	}
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]Finding, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineSecurityReportStatus.
func (in *PipelineSecurityReportStatus) DeepCopy() *PipelineSecurityReportStatus {
	if in == nil {
		return nil
	}
	out := new(PipelineSecurityReportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicySelector) DeepCopyInto(out *PolicySelector) {
	*out = *in
	if in.CICDKinds != nil {
		in, out := &in.CICDKinds, &out.CICDKinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicySelector.
func (in *PolicySelector) DeepCopy() *PolicySelector {
	if in == nil {
		return nil
	}
	out := new(PolicySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyThresholds) DeepCopyInto(out *PolicyThresholds) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyThresholds.
func (in *PolicyThresholds) DeepCopy() *PolicyThresholds {
	if in == nil {
		return nil
	}
	out := new(PolicyThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnforcementAction) DeepCopyInto(out *EnforcementAction) {
	*out = *in
	if in.AlertTarget != nil {
		in, out := &in.AlertTarget, &out.AlertTarget
		*out = new(AlertTarget)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnforcementAction.
func (in *EnforcementAction) DeepCopy() *EnforcementAction {
	if in == nil {
		return nil
	}
	out := new(EnforcementAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertTarget) DeepCopyInto(out *AlertTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertTarget.
func (in *AlertTarget) DeepCopy() *AlertTarget {
	if in == nil {
		return nil
	}
	out := new(AlertTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleOverride) DeepCopyInto(out *RuleOverride) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(RuleOverrideScope)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleOverride.
func (in *RuleOverride) DeepCopy() *RuleOverride {
	if in == nil {
		return nil
	}
	out := new(RuleOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleOverrideScope) DeepCopyInto(out *RuleOverrideScope) {
	*out = *in
	if in.Repositories != nil {
		in, out := &in.Repositories, &out.Repositories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleOverrideScope.
func (in *RuleOverrideScope) DeepCopy() *RuleOverrideScope {
	if in == nil {
		return nil
	}
	out := new(RuleOverrideScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineSourceRef) DeepCopyInto(out *PipelineSourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineSourceRef.
func (in *PipelineSourceRef) DeepCopy() *PipelineSourceRef {
	if in == nil {
		return nil
	}
	out := new(PipelineSourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FindingSummary) DeepCopyInto(out *FindingSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FindingSummary.
func (in *FindingSummary) DeepCopy() *FindingSummary {
	if in == nil {
		return nil
	}
	out := new(FindingSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRef) DeepCopyInto(out *WorkloadRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRef.
func (in *WorkloadRef) DeepCopy() *WorkloadRef {
	if in == nil {
		return nil
	}
	out := new(WorkloadRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Finding) DeepCopyInto(out *Finding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Finding.
func (in *Finding) DeepCopy() *Finding {
	if in == nil {
		return nil
	}
	out := new(Finding)
	in.DeepCopyInto(out)
	return out
}
